export const BROOKE_CONTACT = {
  name: "Brooke Snader",
  fullName: "Brooke Matthew Snader",
  group: "The Scott Gordon Group",
  brokerage: "Douglas Elliman Real Estate",
  legalBrokerage: "Douglas Elliman Florida, LLC d/b/a Douglas Elliman",
  brokerageLicense: "CQ1020232",
  phone: "561-891-0186",
  phoneDisplay: "561-891-0186",
  phoneHref: "tel:+15618910186",
  schemaTelephone: "+1-561-891-0186",
  email: "brooke.snader@gmail.com",
  license: "BK3291335",
  privacyUrl: "https://www.elliman.com/privacy-policy",
  termsUrl: "https://www.elliman.com/terms-of-service",
} as const;

export const teamProfile = {
  name: BROOKE_CONTACT.group,
  displayName: "The Scott Gordon Group",
  brokerage: BROOKE_CONTACT.brokerage,
  legalBrokerage: BROOKE_CONTACT.legalBrokerage,
  brokerageLicense: BROOKE_CONTACT.brokerageLicense,
  presentedBy: "Presented by The Scott Gordon Group at Douglas Elliman",
  marketPosition: "Palm Beach waterfront and West Palm Beach new-construction advisory",
  photo: "/assets/team/scott-gordon-group-team-v01.jpg",
  photoAlt: "Scott Gordon, Mindy Gordon, and Brooke Snader of The Scott Gordon Group at Douglas Elliman",
  logoLockup: "/assets/team/scott-gordon-group-logo-lockup-v01.jpg",
  logoMark: "/assets/team/scott-gordon-group-logo-mark-v01.jpg",
  logoAlt: "Scott Gordon Group logo",
} as const;

export const advisorProfile = {
  name: BROOKE_CONTACT.name,
  title: "Broker Associate",
  group: BROOKE_CONTACT.group,
  brokerage: BROOKE_CONTACT.brokerage,
  brokerageLicense: BROOKE_CONTACT.brokerageLicense,
  mobile: BROOKE_CONTACT.phoneDisplay,
  mobileHref: BROOKE_CONTACT.phoneHref,
  schemaTelephone: BROOKE_CONTACT.schemaTelephone,
  license: BROOKE_CONTACT.license,
  email: BROOKE_CONTACT.email,
  privacyUrl: BROOKE_CONTACT.privacyUrl,
  termsUrl: BROOKE_CONTACT.termsUrl,
} as const;
