#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { getSchemaSafeProjectFacts } from "../../src/lib/projectIntelligence.ts";
import { projectIntelligenceRegistryEntries } from "../../src/lib/projectIntelligenceRegistry.ts";

const workspace = process.cwd();
const outputPath = path.join(workspace, "src/generated/projectSchemaSafe.json");
const publicRuntimePath = path.join(workspace, "src/generated/projectSchemaRuntime.ts");
const checkOnly = process.argv.includes("--check");
const projects = projectIntelligenceRegistryEntries
  .filter((entry) => entry.publicationState === "published")
  .map((entry) => getSchemaSafeProjectFacts(entry.publicSlug));
const output = `${JSON.stringify({ version: 1, projects }, null, 2)}\n`;
const runtimeProjects = projects.map((project) => ({
  identity: project.identity,
  safeFields: Object.fromEntries(
    Object.entries(project.safeFields).filter(([key]) =>
      ["name", "route", "url", "corridor", "status", "delivery", "residenceCount", "address"].includes(key),
    ),
  ),
}));
const runtimeOutput = `// Generated by research/scripts/generate-project-schema-safe.ts. Do not edit directly.\n// Public runtime projection: review workflow state is intentionally excluded.\n\nexport const generatedProjectSchemaFacts = ${JSON.stringify(runtimeProjects, null, 2)} as const;\n`;

if (checkOnly) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== output) {
    console.error("src/generated/projectSchemaSafe.json is stale. Run npm run research:project-schema-safe.");
    process.exit(1);
  }
  if (!fs.existsSync(publicRuntimePath) || fs.readFileSync(publicRuntimePath, "utf8") !== runtimeOutput) {
    console.error("src/generated/projectSchemaRuntime.ts is stale. Run npm run research:project-schema-safe.");
    process.exit(1);
  }
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
  fs.writeFileSync(publicRuntimePath, runtimeOutput);
}

console.log(JSON.stringify({
  projectSchemaSafe: checkOnly ? "checked" : "generated",
  projects: projects.length,
  emittedAddresses: projects.filter((project) => project.safeFields.address).length,
  omittedFields: projects.reduce((sum, project) => sum + project.omittedFields.length, 0),
}, null, 2));
