from pathlib import Path
root = Path.cwd()
# Audit-only adapters: preserve every payload/privacy/visual assertion.
# No application files, account settings, endpoint requests or deployment changes.
s = (root/'research/scripts/check-comparisons.mjs').read_text()
s = s.replace('const origin=`http://127.0.0.1:${server.address().port}`;', "const origin='https://www.wpbnewconstruction.com';")
s = s.replace("const sitemap=await fs.readFile(path.join(dist,'sitemap.xml'),'utf8');", "const sitemap=await (await fetch(origin+'/sitemap.xml')).text();")
s = s.replace("const html=await fs.readFile(path.join(dist,c.path,'index.html'),'utf8');", "const live=await fetch(origin+c.path,{headers:{'Cache-Control':'no-cache'}});assert.equal(live.status,200);const html=await live.text();")
s = s.replace("testedSha:execFileSync", "origin,deployedSha:process.env.DEPLOYED_SHA,testedSha:execFileSync")
(root/'research/scripts/check-comparisons-live.tmp.mjs').write_text(s)
s = (root/'research/scripts/check-corridor-growth.mjs').read_text()
s = s.replace('const origin=`http://127.0.0.1:${server.address().port}`;', 'const origin=commercialOrigin;')
s = s.replace("const scope=javaScriptEnabled ? '#app ' : '';", "const scope=javaScriptEnabled ? '#app .site-shell ' : '';")
s = s.replace("const sitemap=await fs.readFile('dist/sitemap.xml','utf8');", "const sitemap=await (await fetch(origin+'/sitemap.xml')).text();")
s = s.replace("const html=await fs.readFile(path.join(dist,c.path.slice(1),'index.html'),'utf8');", "const live=await fetch(origin+c.path);assert.equal(live.status,200);const html=await live.text();")
s = s.replace("await fs.access(path.join(dist,href.slice(1),path.extname(href)?'':'index.html'));", "assert.equal((await fetch(origin+href,{method:'HEAD'})).status,200,href);")
s = s.replace("await assert.rejects(fs.access('dist/floorplans/alba-palm-beach/residence-d/index.html'));", "assert.equal((await fetch(origin+'/floorplans/alba-palm-beach/residence-d/')).status,404);")
s = s.replace('  const key=Object.keys(pages)', "  if(javaScriptEnabled&&route==='/floorplans/olara/residence-d/')await page.waitForFunction(()=>window.wpbAnalyticsQueue?.some(e=>e.eventName==='page_view'));\n  const key=Object.keys(pages)")
s = s.replace('testedSha:sha,status:', 'origin,deployedSha:process.env.DEPLOYED_SHA,checkedAt:new Date().toISOString(),testedSha:sha,status:')
(root/'research/scripts/check-corridors-live.tmp.mjs').write_text(s)
s = (root/'research/scripts/check-maps-keyed.mjs').read_text()
s = s.replace('await verifyProductionMapBundle();', '// Preflight is enforced on the candidate/build; this check reads production.')
s = s.replace("const origin = 'http://127.0.0.1:4173';", "const origin = 'https://www.wpbnewconstruction.com';")
a = s.index('const server = spawn(')
b = s.index('\nlet browser;', a)
s = s[:a] + 'const server = {exitCode:null,kill(){}};' + s[b:]
(root/'research/scripts/check-maps-live.tmp.mjs').write_text(s)
